DROP TABLE IF EXISTS `sessions`;
CREATE TABLE IF NOT EXISTS `sessions`(
    `id` INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `uuid` VARCHAR(255) NOT NULL UNIQUE,
    `name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `user_id` INTEGER UNSIGNED,
    `created_at` TIMESTAMP)
