DROP TABLE IF EXISTS `blogs`;
CREATE TABLE IF NOT EXISTS `blogs`(
    `id` INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `user_id` INTEGER UNSIGNED ,
    `public_flag` boolean,
    `public_date` datetime,
    `title_img` VARCHAR(255),
    `title` VARCHAR(255),
    `body` TEXT,
    `body_img1` VARCHAR(128),
    `body_img2` VARCHAR(128),
    `body_img3` VARCHAR(128),
    `body_img4` VARCHAR(128),
    `body_img5` VARCHAR(128),
    `body_img6` VARCHAR(128),
    `body_img7` VARCHAR(128),
    `body_img8` VARCHAR(128),
    `categorie1` VARCHAR(64),
    `categorie2` VARCHAR(64),
    `categorie3` VARCHAR(64),
    `categorie4` VARCHAR(64),
    `categorie5` VARCHAR(64),
    `categorie6` VARCHAR(64),
    `categorie7` VARCHAR(64),
    `categorie8` VARCHAR(64),
    `created_at` TIMESTAMP,
    `updated_at` TIMESTAMP,
    `deleted_at` TIMESTAMP);
